services:
  dev:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspace:cached
      - /workspace/node_modules
      - /workspace/.venv
    working_dir: /workspace
    command: sleep infinity
    environment:
      - OLLAMA_HOST=http://192.168.7.43:11434
      - LLM_PROVIDER=ollama
      - PYTHONPATH=/workspace
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@localhost:54322/postgres
      - SUPABASE_URL=http://localhost:54321
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
    ports:
      - "8000:8000"
      - "3000:3000"
    network_mode: host

# Use Supabase CLI for local development:
# supabase init
# supabase start
# 
# This provides:
# - PostgreSQL with pgvector at localhost:54322
# - Supabase Studio at localhost:54321
# - Real-time subscriptions
# - Auth (if needed later)
# - Storage (if needed later)